# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('active', models.BooleanField(default=False, verbose_name='is_active')),
                ('date_started', models.DateTimeField(verbose_name='date_started')),
                ('completion_time', models.DateTimeField(verbose_name='completion_time')),
                ('active_users', models.IntegerField(verbose_name='active_users')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('message', models.TextField(verbose_name='message')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Location')),
            ],
        ),
    ]
